[package]
name = "io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aligned-vec = { version = "0.5.0", default-features = false }
librust = { version = "0.1.0", path = "../librust" }
