# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(u-boot/.*)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
  - repo: local
    hooks:
      - id: workspacetest
        name: run tests
        entry: ./run_test.sh
        language: script
        files: \.x$
        always_run: true
      #- id: clippy   # TODO: Enable clippy later once we are more stable
