[target.riscv64qemu]
rustflags = [
    "-C", "link-arg=-Tsrc/arch/riscv64imac/link/link.ldS"
]
runner = "qemu-system-riscv64 -s -M virt -bios default -nographic -kernel"

[build]
target = "src/arch/riscv64imac/link/riscv64qemu.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
