[target.riscv64imac-unknown-none-elf]
runner = "./run_kernel.sh target/riscv64imac-unknown-none-elf/release/kernel_loader"

[build]
target = "riscv64imac-unknown-none-elf"

[unstable]
# build-std = ["core", "compiler_builtins", "alloc"]
