[target.riscv64imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlink.ldS"
]
runner = "qemu-system-riscv64 -s -M virt -bios default -nographic -kernel"

[build]
target = "riscv64imac-unknown-none-elf"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
