[target.riscv64imac-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlink.ldS"
]
runner = "./run_kernel.sh"

[build]
target = "riscv64imac-unknown-none-elf"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
