[package]
name = "init"
version = "0.1.0"
edition = "2021"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
elfloader = "0.16.0"
fdt = "0.1.5"
librust = { version = "0.1.0", path = "../librust" }
regs = { version = "0.1.0", path = "../../support_crates/regs" }
uart_driver = { version = "0.1.0", path = "../../support_crates/uart_driver" }

[build-dependencies]
cc = "1.0.79"
