[package]
name = "init"
version = "0.1.0"
edition = "2021"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elfloader = "0.16.0"
fdt-rs = { version = "0.4.3", default-features = false }
librust = { version = "0.1.0", path = "../librust" }
uart_driver = { version = "0.1.0", path = "../../support_crates/uart_driver" }

[build-dependencies]
cc = "1.0.79"
