[package]
name = "allocators"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ksync = { path = "../ksync" }
thiserror-no-std = "2.0.2"
log = "0.4.19"
static_assertions = "1.1.0"
