[package]
name = "uart_driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regs = { path = "../regs" }
fdt-rs = { version = "0.4.3", default-features = false }
