[package]
name = "virtio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librust = { version = "0.1.0", path = "../librust" }
regs = { version = "0.1.0", path = "../../support_crates/regs" }
