[package]
name = "sbi_log"
description = "A logging implementation which uses an OpenSBI syscall to print characters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbi = "0.2.0"
log = "0.4.17"
